<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cx</string>
		<string>hx</string>
	</array>
	<key>name</key>
	<string>Cx</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash.c</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.c</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.c</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.preprocessor.c</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.preprocessor.c</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#(\w+)\s*(\w*)(?:\(([^)]*)\))?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.c</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.c</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*:\s*([^=]*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t*\b(enum|struct|typedef)\b</string>
			<key>name</key>
			<string>keyword.other.c</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t*\b(break|case|continue|default|do|else|finally|for|goto|if|return|switch|try|unless|until|while)\b</string>
			<key>name</key>
			<string>keyword.control.c</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t*\b(and|not|or|is|catch)\b</string>
			<key>name</key>
			<string>keyword.operator.c</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t*\b(NULL|true|false)\b</string>
			<key>name</key>
			<string>constant.language.c</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\t*\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.c</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method.c</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\t*\b(\w+)(?=\s*((\s\w)|[("]))</string>
			<key>name</key>
			<string>meta.function-call.c</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant-character-escape</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%[.*]*\w</string>
					<key>name</key>
					<string>constant.other.placeholder.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant-character-escape</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>constant-character-escape</key>
		<dict>
			<key>match</key>
			<string>\\x[0-9a-fA-F]{0,2}</string>
			<key>name</key>
			<string>constant.character.escape.c</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cx</string>
	<key>uuid</key>
	<string>90D56E6E-40DA-475D-AECE-EEC9D11446CB</string>
</dict>
</plist>
